### ISSUE TITLE
Remote server docker support?

### ISSUE THREAD

**Issue by rusiaaman** [genular/simon-frontend#46]
**Describe the bug**
Docker on remote server with ports 3011, 3010 opened. Says server is not available. Go to homepage redirects to localhost:3010 instead of remote location.

**To Reproduce**
Instantiate ec2 server with docker. Deploy docker using command in README. Open ports 3010

**Screenshots**

![image](https://user-images.githubusercontent.com/34934104/57060734-14d8d080-6cd8-11e9-8c9b-00a8410d0175.png)

**Desktop (please complete the following information):**
 - OS: Server: Ubuntu 18.04, Client: Ubuntu 16.0x
 - Browser: Firefox 66.0.3 (64-bit) for Ubuntu
 - Version: genular/simon:latest

**Comment by LogIN-** [comment]
Hi @rusiaaman 
You are right prebuilded docker image [that is on dockerhub ](https://cloud.docker.com/u/genular/repository/docker/genular/simon) is intended to be used just on your local machine.

To install SIMON on some remote machine or to use custom hostname to access frontend/backend you need to build that image by yourself and set appropriate configuration variable.

You can find tutorial on our [community forums here](https://community.genular.org/viewtopic.php?f=4&p=4#p4).

Probably instructions can be a bit better. If you need some help installing it contact me on forums.
It would be great if some-kind more detail tutorial would exist regarding that.

**Comment by meganbkratz** [comment]
Hi @LogIN,

Is it still the case that running the SIMON docker container remotely is not supported? This would be an incredibly useful feature.

Unfortunately the genular.org site seems to be down, so I'm unable to access the community forums you mention. If you could post instructions for building a suitable custom container, I'd appreciate it!

Thanks!

**Comment by LogIN-** [comment]
Hi @meganbkratz ,

I agree that would be really good, however its not supported currently out of the box. We had server issue and our HDD died few days ago, that's why forums and site are currently down. Hopefully you will manage to run PANDORA on your local PC till than.

We had a lot of improvements in last few months, with wrapping it all together few days ago, added multiple outcome classification support and some other features, it's still all in testing phase but should work fine.

Just find some relatively good PC and run (and please be sure to delete any old images/containers and volumes!):

```bash
docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --oom-kill-disable --volume genular_frontend_latest:/var/www/genular/pandora --volume genular_backend_latest:/var/www/genular/pandora-backend --volume genular_data_latest:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/pandora:latest
```
